//! Gröbner basis on the sparse polynomial representation.
//!
//! Buchberger's algorithm (naive S-pair enumeration) plus inter-reduction
//! to the canonical reduced basis, built from [`SparsePolynomial`]
//! operations (reduction, S-polynomial, monic scaling). Buchberger
//! criteria and a sparse geobucket are not yet implemented. The reduced
//! Gröbner basis of an ideal under a fixed monomial order is unique, so
//! this agrees term-for-term with the dense engine; `repr_oracle` checks
//! that.

use super::polynomial::PolyRing;
use super::repr::MonomialRepr;
use super::sparse_polynomial::SparsePolynomial;

/// Monic-normalised S-polynomial of two nonzero polynomials:
/// `(1/lc(f))·(L/lm(f))·f − (1/lc(g))·(L/lm(g))·g`, `L = lcm(lm(f), lm(g))`.
pub fn s_polynomial(
    f: &SparsePolynomial,
    g: &SparsePolynomial,
    ring: &PolyRing,
) -> SparsePolynomial {
    let (lmf, lcf) = f.leading_term().expect("s_polynomial: f is nonzero");
    let (lmg, lcg) = g.leading_term().expect("s_polynomial: g is nonzero");
    let l = MonomialRepr::lcm(lmf, lmg);
    let mf = MonomialRepr::div(&l, lmf);
    let mg = MonomialRepr::div(&l, lmg);
    let inv_f = ring.field.inv(lcf).expect("nonzero leading coeff");
    let inv_g = ring.field.inv(lcg).expect("nonzero leading coeff");
    let term_f = SparsePolynomial::from_terms(vec![(mf, inv_f)], ring);
    let term_g = SparsePolynomial::from_terms(vec![(mg, inv_g)], ring);
    let part_f = term_f.mul(f, ring);
    let part_g = term_g.mul(g, ring);
    part_f.sub(&part_g, ring)
}

/// A Gröbner basis of the ideal generated by `gens` (textbook Buchberger,
/// naive pair enumeration). The result is a — not necessarily reduced —
/// Gröbner basis; call [`interreduce`] for the canonical reduced form.
pub fn groebner_basis(gens: Vec<SparsePolynomial>, ring: &PolyRing) -> Vec<SparsePolynomial> {
    let mut basis: Vec<SparsePolynomial> =
        gens.into_iter().filter(|p| !p.is_zero()).collect();

    let mut pairs: std::collections::VecDeque<(usize, usize)> =
        std::collections::VecDeque::new();
    for i in 0..basis.len() {
        for j in (i + 1)..basis.len() {
            pairs.push_back((i, j));
        }
    }

    while let Some((i, j)) = pairs.pop_front() {
        let s = s_polynomial(&basis[i], &basis[j], ring);
        let refs: Vec<&SparsePolynomial> = basis.iter().collect();
        let r = s.reduce_by_refs(&refs, ring);
        if !r.is_zero() {
            let idx = basis.len();
            basis.push(r);
            for k in 0..idx {
                pairs.push_back((k, idx));
            }
        }
    }
    basis
}

/// Inter-reduce a basis into the canonical reduced Gröbner basis: drop
/// zeros, collapse to `{1}` if the ideal is the whole ring, make every
/// element monic, drop elements whose leading term is divisible by
/// another's, and tail-reduce each survivor by the others. Mirrors the
/// dense `buchberger::interreduce`.
pub fn interreduce(mut basis: Vec<SparsePolynomial>, ring: &PolyRing) -> Vec<SparsePolynomial> {
    basis.retain(|p| !p.is_zero());
    if basis.iter().any(|p| p.is_constant()) {
        return vec![SparsePolynomial::constant(ring.field.one(), ring)];
    }
    for p in basis.iter_mut() {
        *p = p.make_monic(ring);
    }
    // Sort by leading monomial descending (deterministic output).
    basis.sort_by(|a, b| {
        let la = a.leading_monomial().unwrap();
        let lb = b.leading_monomial().unwrap();
        MonomialRepr::cmp_with_order(lb, la, ring.order)
    });
    // Minimise: drop any element whose leading monomial is strictly
    // divisible by another's.
    let mut keep = vec![true; basis.len()];
    for i in 0..basis.len() {
        if !keep[i] {
            continue;
        }
        let li = basis[i].leading_monomial().unwrap().clone();
        for j in 0..basis.len() {
            if i == j || !keep[j] {
                continue;
            }
            let lj = basis[j].leading_monomial().unwrap();
            if MonomialRepr::divides(&li, lj) && &li != lj {
                keep[j] = false;
            }
        }
    }
    let mut filtered: Vec<SparsePolynomial> = basis
        .into_iter()
        .zip(keep)
        .filter_map(|(p, k)| k.then_some(p))
        .collect();

    // Single-pass tail reduction (LTs are pairwise incomparable after
    // minimisation, so one pass reaches the reduced form).
    let n = filtered.len();
    for i in 0..n {
        let red = {
            let others: Vec<&SparsePolynomial> = filtered
                .iter()
                .enumerate()
                .filter(|(j, p)| *j != i && !p.is_zero())
                .map(|(_, p)| p)
                .collect();
            if others.is_empty() {
                None
            } else {
                Some(filtered[i].reduce_by_refs(&others, ring))
            }
        };
        if let Some(red) = red {
            filtered[i] = if red.is_zero() {
                SparsePolynomial::zero()
            } else {
                red.make_monic(ring)
            };
        }
    }
    filtered.retain(|p| !p.is_zero());
    filtered
}
