[package]
name = "picus-solver"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
description = "Pure Rust finite field SMT solver for Picus"

[dependencies]
num-bigint.workspace = true
num-traits.workspace = true
log.workspace = true
thiserror.workspace = true
oorandom = "11.1"
picus-core = { path = "../picus-core" }
picus-metric-macros = { path = "../picus-metric-macros" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "solver_bench"
harness = false

[[bench]]
name = "cdclt_bench"
harness = false

[[bench]]
name = "smt2_bench"
harness = false
