[ground-truth]
verdict = "safe"
constraints = 24316
wires = 24315
pub_outputs = 0
priv_inputs = 7
prime = "bn254"

[picus-0]
verdict = "safe"
time_ms = 2257

[picus-1]
verdict = "safe"
time_ms = 6738
