[ground-truth]
verdict = "safe"
constraints = 42920
wires = 43661
pub_outputs = 0
priv_inputs = 770
prime = "bn254"

[picus-0]
verdict = "safe"
time_ms = 828

[picus-1]
verdict = "safe"
time_ms = 2599
