[ground-truth]
verdict = "safe"
constraints = 21737
wires = 21736
pub_outputs = 0
priv_inputs = 7
prime = "bn254"

[picus-0]
verdict = "safe"
time_ms = 1169

[picus-1]
verdict = "safe"
time_ms = 3577
