[ground-truth]
verdict = "unknown"
constraints = 67
wires = 72
pub_outputs = 2
priv_inputs = 4
prime = "bn254"

[picus-0]
verdict = "timeout"
time_ms = 30034

[picus-1]
verdict = "timeout"
time_ms = 30020
