[ground-truth]
verdict = "unknown"
constraints = 90
wires = 96
pub_outputs = 4
priv_inputs = 5
prime = "bn254"

[picus-0]
verdict = "timeout"
time_ms = 30029

[picus-1]
verdict = "timeout"
time_ms = 30038
