[ground-truth]
verdict = "unknown"
constraints = 90
wires = 97
pub_outputs = 4
priv_inputs = 6
prime = "bn254"

[picus-0]
verdict = "timeout"
time_ms = 30026

[picus-1]
verdict = "timeout"
time_ms = 30037
