//! Spec-driven tests for [`super::sparse_geobucket::reduce`].
//!
//! The geobucket reducer is the production multivariate-division path for
//! the sparse representation. Spec, per the source docstring on `reduce`:
//!   - leading terms are popped in DESCENDING ring order;
//!   - each leading term is either cancelled by the FIRST divisor whose LT
//!     divides it (subtract scaled tail), or appended to the result;
//!   - the result stream is descending and duplicate-free (canonical).
//!
//! `SparsePolynomial::reduce_by_refs` is the public entry point; the doc
//! says it agrees term-for-term with the naive O(n)-per-step reducer
//! `reduce_by_refs_naive` and with the dense reducer (per `repr_oracle`).

use crate::ff::field::PrimeField;
use crate::ff::monomial::MonomialOrder;
use crate::ff::polynomial::PolyRing;
use crate::ff::repr::MonomialRepr;
use crate::ff::sparse_monomial::SparseMonomial;
use crate::ff::sparse_polynomial::SparsePolynomial;
use crate::timeout::CancelToken;
use num_bigint::BigUint;
use std::sync::Arc;

// ── helpers ─────────────────────────────────────────────────────────────

fn ring(prime: u64, n_vars: usize) -> Arc<PolyRing> {
    let f = PrimeField::new(BigUint::from(prime));
    let names: Vec<String> = (0..n_vars).map(|i| format!("x{i}")).collect();
    PolyRing::new(f, names, MonomialOrder::DegRevLex)
}

fn sp(items: Vec<(Vec<u16>, i64)>, r: &PolyRing) -> SparsePolynomial {
    let f = &r.field;
    let terms: Vec<(SparseMonomial, crate::ff::field::FieldElem)> = items
        .into_iter()
        .map(|(e, c)| (<SparseMonomial as MonomialRepr>::from_exponents(e), f.from_i64(c)))
        .collect();
    SparsePolynomial::from_terms(terms, r)
}

fn sparse_eq(a: &SparsePolynomial, b: &SparsePolynomial, r: &PolyRing) -> bool {
    if a.num_terms() != b.num_terms() {
        return false;
    }
    for i in 0..a.num_terms() {
        let (ma, ca) = a.term_at(i).unwrap();
        let (mb, cb) = b.term_at(i).unwrap();
        if ma != mb || !r.field.eq(ca, cb) {
            return false;
        }
    }
    true
}

// ── (1) Spec corners ────────────────────────────────────────────────────

#[test]
fn prop_reduce_empty_divisors_is_identity() {
    // No divisors ⇒ NF(p) = p (nothing to cancel).
    let r = ring(101, 3);
    let p = sp(vec![(vec![2, 1, 0], 3), (vec![0, 0, 1], 7), (vec![0, 0, 0], 1)], &r);
    let nf = p.reduce_by_refs(&[], &r);
    assert!(sparse_eq(&p, &nf, &r));
}

#[test]
fn prop_reduce_zero_subject_stays_zero() {
    // NF(0) = 0 regardless of divisor set.
    let r = ring(101, 3);
    let d = sp(vec![(vec![1, 0, 0], 1)], &r);
    let nf = SparsePolynomial::zero().reduce_by_refs(&[&d], &r);
    assert!(nf.is_zero());
}

#[test]
fn prop_reduce_p_mod_p_is_zero() {
    // NF(p) modulo [p] = 0 for any nonzero p.
    let r = ring(101, 3);
    for p in [
        sp(vec![(vec![3, 1, 0], 4), (vec![1, 0, 1], 2), (vec![0, 0, 0], 5)], &r),
        sp(vec![(vec![2, 0, 0], 1), (vec![0, 1, 1], 7)], &r),
    ] {
        assert!(p.reduce_by_refs(&[&p], &r).is_zero(),
            "NF(p mod [p]) should be 0");
    }
}

#[test]
fn prop_reduce_const_times_p_mod_p_is_zero() {
    // q*p mod [p] = 0 (membership in the ideal generated by p).
    let r = ring(101, 3);
    let p = sp(vec![(vec![2, 0, 0], 1), (vec![0, 1, 0], -1)], &r); // x0^2 - x1
    let q = sp(vec![(vec![1, 0, 0], 1), (vec![0, 0, 1], 1), (vec![0, 0, 0], 7)], &r);
    let qp = q.mul(&p, &r);
    assert!(qp.reduce_by_refs(&[&p], &r).is_zero());
}

#[test]
fn prop_reduce_irreducible_subject_is_identity() {
    // If no divisor LT divides any term of `p`, NF(p) = p.
    let r = ring(101, 3);
    // p uses only x2; divisor LT uses only x0 — they cannot divide.
    let p = sp(vec![(vec![0, 0, 3], 1), (vec![0, 0, 1], 1), (vec![0, 0, 0], 4)], &r);
    let d = sp(vec![(vec![2, 0, 0], 1), (vec![0, 0, 0], 5)], &r);
    let nf = p.reduce_by_refs(&[&d], &r);
    assert!(sparse_eq(&p, &nf, &r),
        "irreducible subject must come out unchanged");
}

// ── (2) Differential oracle: naive ≡ geobucket ≡ dense ─────────────────

#[test]
fn prop_reduce_geobucket_matches_naive() {
    // Per docstring: `reduce_by_refs` (geobucket) and `reduce_by_refs_naive`
    // use the SAME divisor-selection rule (first divisor by index whose LT
    // divides) and must produce identical normal forms.
    let r = ring(101, 3);
    let p = sp(
        vec![
            (vec![3, 2, 0], 1),
            (vec![2, 1, 1], 4),
            (vec![1, 0, 2], 2),
            (vec![0, 1, 0], 7),
            (vec![0, 0, 0], 9),
        ],
        &r,
    );
    let d1 = sp(vec![(vec![2, 0, 0], 1), (vec![0, 1, 0], -1)], &r); // x0^2 - x1
    let d2 = sp(vec![(vec![1, 1, 0], 1), (vec![0, 0, 1], -1)], &r); // x0*x1 - x2
    let d3 = sp(vec![(vec![0, 0, 2], 1), (vec![0, 0, 0], -1)], &r); // x2^2 - 1
    let divs: Vec<&SparsePolynomial> = vec![&d1, &d2, &d3];
    let nf_naive = p.reduce_by_refs_naive(&divs, &r);
    let nf_geo = p.reduce_by_refs(&divs, &r);
    assert!(sparse_eq(&nf_naive, &nf_geo, &r),
        "geobucket and naive reducers disagree on NF");
}

#[test]
fn prop_reduce_result_descending_canonical() {
    // Doc: "result stream is descending and duplicate-free, so it is
    // canonical." Pin via cmp_with_order between consecutive terms.
    let r = ring(101, 4);
    let p = sp(
        vec![
            (vec![4, 0, 0, 0], 3),
            (vec![3, 1, 0, 0], 2),
            (vec![0, 0, 2, 1], 5),
            (vec![0, 0, 0, 3], 1),
            (vec![0, 0, 0, 0], 7),
        ],
        &r,
    );
    let d = sp(vec![(vec![3, 0, 0, 0], 1), (vec![0, 0, 0, 0], -1)], &r); // x0^3 - 1
    let nf = p.reduce_by_refs(&[&d], &r);
    for i in 1..nf.num_terms() {
        let (a, _) = nf.term_at(i - 1).unwrap();
        let (b, _) = nf.term_at(i).unwrap();
        assert_eq!(
            a.cmp_with_order(b, r.order),
            std::cmp::Ordering::Greater,
            "result not strictly descending at idx {i}"
        );
    }
}

// ── (3) Cancellation handling inside the geobucket ─────────────────────

#[test]
fn prop_reduce_cancels_all_terms() {
    // Pick p such that p mod p = 0 — exercises the cross-bucket
    // cancellation path inside `pop_leading_term`.
    let r = ring(101, 3);
    let p = sp(
        vec![
            (vec![4, 0, 0], 1),
            (vec![2, 1, 0], 2),
            (vec![1, 0, 1], 3),
            (vec![0, 0, 0], 5),
        ],
        &r,
    );
    assert!(p.reduce_by_refs(&[&p], &r).is_zero());
}

#[test]
fn prop_reduce_inside_ideal_two_generators() {
    // (a*p + b*q) mod [p, q] = 0 — ideal membership through reduction.
    let r = ring(101, 3);
    let p = sp(vec![(vec![2, 0, 0], 1), (vec![0, 1, 0], -1)], &r); // x0^2 - x1
    let q = sp(vec![(vec![0, 2, 0], 1), (vec![0, 0, 1], -1)], &r); // x1^2 - x2
    let a = sp(vec![(vec![1, 0, 0], 1), (vec![0, 0, 1], 2)], &r);
    let b = sp(vec![(vec![0, 1, 0], 3), (vec![0, 0, 0], 7)], &r);
    let sum = a.mul(&p, &r).add(&b.mul(&q, &r), &r);
    let nf = sum.reduce_by_refs(&[&p, &q], &r);
    assert!(nf.is_zero(), "element of <p,q> should reduce to 0");
}

// ── (4) Divisor-order dependency (documented spec) ─────────────────────

#[test]
fn prop_reduce_divisor_first_match_wins() {
    // `reduce` selects "the FIRST divisor whose LT divides the current
    // monomial". Reorder the divisor list and verify the same NF computed
    // by the naive reducer (same selection rule) is produced for both
    // orderings the geobucket sees.
    let r = ring(101, 2);
    let p = sp(vec![(vec![2, 0], 1), (vec![0, 1], 1)], &r);
    let d1 = sp(vec![(vec![1, 0], 1), (vec![0, 0], -1)], &r); // x0 - 1
    let d2 = sp(vec![(vec![2, 0], 1), (vec![0, 0], -1)], &r); // x0^2 - 1
    // Order A: d1 first. x0^2 reducible by d1, so subtracted via d1.
    let order_a: Vec<&SparsePolynomial> = vec![&d1, &d2];
    let nf_a_geo = p.reduce_by_refs(&order_a, &r);
    let nf_a_naive = p.reduce_by_refs_naive(&order_a, &r);
    assert!(sparse_eq(&nf_a_geo, &nf_a_naive, &r),
        "order A: geobucket disagrees with naive");
    // Order B: d2 first. Now d2's LT (x0^2) divides only x0^2, so first
    // step uses d2; remaining can still hit d1.
    let order_b: Vec<&SparsePolynomial> = vec![&d2, &d1];
    let nf_b_geo = p.reduce_by_refs(&order_b, &r);
    let nf_b_naive = p.reduce_by_refs_naive(&order_b, &r);
    assert!(sparse_eq(&nf_b_geo, &nf_b_naive, &r),
        "order B: geobucket disagrees with naive");
}

// ── (5) Cancel token ────────────────────────────────────────────────────

#[test]
fn prop_reduce_cancel_small_subject_canonical() {
    // Cancel-aware reduction with a small subject (well below the
    // CANCEL_STRIDE check threshold) — even with a cancelled token, no
    // cancel check ever fires for inputs this small. Either way, the
    // resulting SparsePolynomial must be canonical (descending,
    // duplicate-free).
    let r = ring(101, 3);
    let p = sp(
        vec![(vec![3, 0, 0], 1), (vec![2, 1, 0], 2), (vec![0, 0, 0], 5)],
        &r,
    );
    let d = sp(vec![(vec![1, 0, 0], 1), (vec![0, 0, 0], -1)], &r); // x0 - 1
    let token = CancelToken::new();
    token.cancel(); // cancelled, but stride may not trip on this small input
    let nf = p.reduce_by_refs_cancel(&[&d], &r, Some(&token));
    for i in 1..nf.num_terms() {
        let (a, _) = nf.term_at(i - 1).unwrap();
        let (b, _) = nf.term_at(i).unwrap();
        assert_eq!(a.cmp_with_order(b, r.order), std::cmp::Ordering::Greater);
    }
}

#[test]
fn prop_reduce_cancel_uncancelled_token_equals_uncancelled() {
    // With a fresh (uncancelled) token, the result must equal a normal
    // reduction (cancel never fires).
    let r = ring(101, 3);
    let p = sp(
        vec![
            (vec![3, 0, 0], 1),
            (vec![2, 1, 0], 2),
            (vec![0, 0, 0], 5),
        ],
        &r,
    );
    let d = sp(vec![(vec![1, 0, 0], 1), (vec![0, 0, 0], -1)], &r); // x0 - 1
    let token = CancelToken::new();
    let nf_a = p.reduce_by_refs_cancel(&[&d], &r, Some(&token));
    let nf_b = p.reduce_by_refs(&[&d], &r);
    assert!(sparse_eq(&nf_a, &nf_b, &r));
}

// ── (6) Stress: many small additions force cascade ─────────────────────

#[test]
fn prop_reduce_dense_subject_descending() {
    // 50-term subject reduced by a single divisor. Pin: NF stays canonical
    // (descending, duplicate-free).
    let r = ring(101, 3);
    let mut items = Vec::new();
    for i in 0..50u16 {
        items.push((vec![i % 4, (i / 4) % 4, (i / 16) % 4], (i as i64 % 50) + 1));
    }
    let p = sp(items, &r);
    let d = sp(vec![(vec![2, 0, 0], 1), (vec![0, 0, 0], -1)], &r);
    let nf = p.reduce_by_refs(&[&d], &r);
    for i in 1..nf.num_terms() {
        let (a, _) = nf.term_at(i - 1).unwrap();
        let (b, _) = nf.term_at(i).unwrap();
        assert_eq!(
            a.cmp_with_order(b, r.order),
            std::cmp::Ordering::Greater,
            "result not descending at idx {i}"
        );
    }
    // All NF coefficients nonzero (canonical invariant).
    for i in 0..nf.num_terms() {
        let (_, c) = nf.term_at(i).unwrap();
        assert!(!r.field.is_zero(c), "zero coeff in NF at idx {i}");
    }
}

// ── (7) Small-prime sanity ──────────────────────────────────────────────

#[test]
fn prop_reduce_gf7_consistency() {
    // Smaller prime: still NF(p) mod p = 0; naive ≡ geobucket.
    let r = ring(7, 3);
    let p = sp(vec![(vec![2, 1, 0], 3), (vec![0, 0, 1], 5), (vec![0, 0, 0], 4)], &r);
    let d = sp(vec![(vec![2, 0, 0], 1), (vec![0, 1, 0], -1)], &r);
    let nf_geo = p.reduce_by_refs(&[&d], &r);
    let nf_naive = p.reduce_by_refs_naive(&[&d], &r);
    assert!(sparse_eq(&nf_geo, &nf_naive, &r));
    // p mod [p] = 0 in GF(7) too.
    assert!(p.reduce_by_refs(&[&p], &r).is_zero());
}
